[الجهة]
بلدية_رأس_الخيمة = "RAK-MUN!93vB#2025"
محاكم_رأس_الخيمة = "RAK-CR!84zQ@2025"
النيابة_العامة_في_رأس_الخيمة = "RAK-PR!77xL&2025"
دائرة_التنمية_الاقتصادية = "RAK-DED!66pK*2025"
جمارك_رأس_الخيمة = "RAK-CU!59tM%2025"
هيئة_حماية_البيئة_والتنمية = "RAK-EN!48rN^2025"
الأمانة_العامة_للمجلس_التنفيذي = "RAK-EC!99Adm@2025"
