[الجهة]
"بلدية رأس الخيمة"="RAK-MUN!93vB#2025"
"محاكم رأس الخيمة"="RAK-CR!84zQ@2025"
"النيابة العامة في رأس الخيمة"="RAK-PR!77xL&2025"
"دائرة التنمية الاقتصادية"="RAK-DED!66pK*2025"
"جمارك رأس الخيمة"="RAK-CU!59tM%2025"
"هيئة حماية البيئة والتنمية"="RAK-EN!48rN^2025"
"الأمانة العامة للمجلس التنفيذي"="RAK-EC!99Adm@2025"
